### ISSUE TITLE
[feature request] migrate from xhr2 to fetch(?)

### ISSUE THREAD

**Issue by ghost** [sc0Vu/doh-js-client#13]
it would probably simplify stuff  
plus it will reduce the dependency-list <sup><a href="https://gist.github.com/eladkarako/db5ecd9d86a09f27bd3197d0cc9f756a#file-nodejs-fetch-api-extended-example-can-adjust-to-browser-with-some-advance-stuff-such-as-options-headers-and-newly-added-self-managed-auto-timeout-js">1</a></sup>

**Comment by sc0Vu** [comment]
Hi @eladkarako 

Thanks, using `fetch` is a good idea. I'll check how many browser / nodejs support it.

**Comment by ghost** [comment]
after inspecting it further,  
node's native `https` library along with a simpler encoder and decoder for the payload stream, is probably a much better option.
